version: '3'

services:
    mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        restart: always
        environment:
          - MYSQL_ROOT_PASSWORD=rootPass
          - MYSQL_DATABASE=blog
          - MYSQL_USER=blog
          - MYSQL_PASSWORD=secret
        volumes:
          - dbdata:/var/lib/mysql

volumes:
    dbdata:
